import requests
from PIL import Image
from io import BytesIO
import os


def get_image_url(character_name, api_key, search_engine_id):
    search_url = "https://www.googleapis.com/customsearch/v1"
    params = {
        'q': character_name,
        'cx': search_engine_id,
        'key': api_key,
        'searchType': 'image',
        'num': 1
    }
    response = requests.get(search_url, params=params)
    results = response.json()

    if 'items' in results:
        return results['items'][0]['link']
    return None


# Example usage
api_key = 'AIzaSyAwLCSwh1tIlcwoGjAK_YJStyZiNP4LSaI'
search_engine_id = '013942479656389735329:lynwfbowoeo'
character_names = {
    'LEGO Police Car': '',
    'LEGO Aerial Squad Car': '',
    'LEGO Missile Striker': '',
    'LEGO Gravity Sprinter': '',
    'LEGO Street Shredder': '',
    'LEGO Sky Clobberer': '',
    'LEGO Batmobile': '',
    'LEGO Batblaster': '',
    'LEGO Sonic Batray': '',
    'LEGO Bennys Spaceship': '',
    'LEGO Lasercraft': '',
    'LEGO The Annihilator': '',
    'LEGO DeLorean Time Machine': '',
    'LEGO Electric Time Machine': '',
    'LEGO Ultra Time Machine': '',
    'LEGO Hoverboard': '',
    'LEGO Cyclone Board': '',
    'LEGO Ultimate Hoverjet': '',
    'LEGO Eagle Interceptor': '',
    'LEGO Eagle Sky Blazer': '',
    'LEGO Eagle Swoop Diver': '',
    'LEGO Swamp Skimmer': '',
    'LEGO Craggers Fireship': '',
    'LEGO Croc Command Sub': '',
    'LEGO Cyber-Guard': '',
    'LEGO Cyber-Wrecker': '',
    'LEGO Laser Robot Walker': '',
    'LEGO K-9': '',
    'LEGO K-9 Ruff Rover': '',
    'LEGO K-9 Laser Cutter': '',
    'LEGO TARDIS': '',
    'LEGO Laser-Pulse TARDIS': '',
    'LEGO Energy-Burst TARDIS': '',
    'LEGO Emmets Excavator': '',
    'LEGO Destroy Dozer': '',
    'LEGO Destruct-o-Mech': '',
    'LEGO Winged Monkey': '',
    'LEGO Battle Monkey': '',
    'LEGO Commander Monkey': '',
    'LEGO Axe Chariot': '',
    'LEGO Axe Hurler': '',
    'LEGO Soaring Chariot': '',
    'LEGO Shelob the Great': '',
    'LEGO 8-Legged Stalker': '',
    'LEGO Poison Slinger': '',
    'LEGO Homers Car': '',
    'LEGO The SubmaHomer': '',
    'LEGO The Homercraft': '',
    'LEGO Taunt-o-Vision': '',
    'LEGO The MechaHomer': '',
    'LEGO Blast Cam': '',
    'LEGO Velociraptor': '',
    'LEGO Venom Raptor': '',
    'LEGO Spike Attack Raptor': '',
    'LEGO Gyrosphere': '',
    'LEGO Sonic Beam Gyrosphere': '',
    'LEGO Speed Boost Gyrosphere': '',
    'LEGO Clown Bike': '',
    'LEGO Cannon Bike': '',
    'LEGO Anti-Gravity Rocket Bike': '',
    'LEGO Mighty Lion Rider': '',
    'LEGO Lion Blazer': '',
    'LEGO Fire Lion': '',
    'LEGO Arrow Launcher': '',
    'LEGO Seeking Shooter': '',
    'LEGO Triple Ballista': '',
    'LEGO Mystery Machine': '',
    'LEGO Mystery Tow & Go': '',
    'LEGO Mystery Monster': '',
    'LEGO Boulder Bomber': '',
    'LEGO Boulder Blaster': '',
    'LEGO Cyclone Jet': '',
    'LEGO Storm Fighter': '',
    'LEGO Lightning Jet': '',
    'LEGO Electro-Shooter': '',
    'LEGO Blade Bike': '',
    'LEGO Flight Fire Bike': '',
    'LEGO Blades of Fire': '',
    'LEGO Samurai Mech': '',
    'LEGO Samurai Shooter': '',
    'LEGO Soaring Samurai Mech': '',
    'LEGO Companion Cube': '',
    'LEGO Laser Deflector': '',
    'LEGO Gold Heart Emitter': '',
    'LEGO Sentry Turret': '',
    'LEGO Turret Striker': '',
    'LEGO Flight Turret Carrier': '',
    'LEGO Scooby Snack': '',
    'LEGO Scooby Fire Snack': '',
    'LEGO Scooby Ghost Snack': '',
    'LEGO Cloud Cuckoo Car': '',
    'LEGO X-Stream Soaker': '',
    'LEGO Rainbow Cannon': '',
    'LEGO Invisible Jet': '',
    'LEGO Laser Shooter': '',
    'LEGO Torpedo Bomber': '',
    'LEGO NinjaCopter': '',
    'LEGO Glaciator': '',
    'LEGO Freeze Fighter': '',
    'LEGO Travelling Time Train': '',
    'LEGO Flight Time Train': '',
    'LEGO Missile Blast Time Train': '',
    'LEGO Aqua Watercraft': '',
    'LEGO Seven Seas Speeder': '',
    'LEGO Trident of Fire': '',
    'LEGO Drill Driver': '',
    'LEGO Bane Dig n Drill': '',
    'LEGO Bane Drill n Blast': '',
    'LEGO Quinn Mobile': '',
    'LEGO Quinn Ultra Racer': '',
    'LEGO Missile Launcher': '',
    'LEGO The Jokers Chopper': '',
    'LEGO Mischievous Missile Blaster': '',
    'LEGO Lock n Laser Jet': '',
    'LEGO Hover Pod': '',
    'LEGO Krypton Striker': '',
    'LEGO Super Stealth Pod': '',
    'LEGO Dalek': '',
    'LEGO Fire n Ride Dalek': '',
    'LEGO Silver Shooter Dalek': '',
    'LEGO Ecto-1': '',
    'LEGO Ecto-1 Blaster': '',
    'LEGO Ecto-1 Water Diver': '',
    'LEGO Ghost Trap': '',
    'LEGO Ghost Stun n Trap': '',
    'LEGO Proton Zapper': '',
    'LEGO Unknown 1126': '',
    'LEGO Unknown 1127': '',
    'LEGO Unknown 1128': '',
    'LEGO Unknown 1129': '',
    'LEGO Unknown 1130': '',
    'LEGO Unknown 1131': '',
    'LEGO Lloyds Golden Dragon': '',
    'LEGO Sword Projector Dragon': '',
    'LEGO Unknown 1134': '',
    'LEGO Unknown 1135': '',
    'LEGO Unknown 1136': '',
    'LEGO Unknown 1137': '',
    'LEGO Unknown 1138': '',
    'LEGO Unknown 1139': '',
    'LEGO Unknown 1140': '',
    'LEGO Unknown 1141': '',
    'LEGO Unknown 1142': '',
    'LEGO Unknown 1143': '',
    'LEGO Mega Flight Dragon': '',
    'LEGO Unknown 1145': '',
    'LEGO Unknown 1146': '',
    'LEGO Unknown 1147': '',
    'LEGO Unknown 1148': '',
    'LEGO Unknown 1149': '',
    'LEGO Unknown 1150': '',
    'LEGO Unknown 1151': '',
    'LEGO Unknown 1152': '',
    'LEGO Unknown 1153': '',
    'LEGO Unknown 1154': '',
    'LEGO Flying White Dragon': '',
    'LEGO Golden Fire Dragon': '',
    'LEGO Ultra Destruction Dragon': '',
    'LEGO Arcade Machine': '',
    'LEGO 8-Bit Shooter': '',
    'LEGO The Pixelator': '',
    'LEGO G-6155 Spy Hunter': '',
    'LEGO Interdiver': '',
    'LEGO Aerial Spyhunter': '',
    'LEGO Slime Shooter': '',
    'LEGO Slime Exploder': '',
    'LEGO Slime Streamer': '',
    'LEGO Terror Dog': '',
    'LEGO Terror Dog Destroyer': '',
    'LEGO Soaring Terror Dog': '',
    'LEGO Ancient Psychic Tandem War Elephant': '',
    'LEGO Cosmic Squid': '',
    'LEGO Psychic Submarine': '',
    'LEGO BMO': '',
    'LEGO DOGMO': '',
    'LEGO SNAKEMO': '',
    'LEGO Jakemobile': '',
    'LEGO Snail Dude Jake': '',
    'LEGO Hover Jake': '',
    'LEGO Lumpy Car': '',
    'LEGO Lumpy Land Whale': '',
    'LEGO Lumpy Truck': '',
    'LEGO Lunatic Amp': '',
    'LEGO Shadow Scorpion': '',
    'LEGO Heavy Metal Monster': '',
    'LEGO B.A.s Van': '',
    'LEGO Fool Smasher': '',
    'LEGO Pain Plane': '',
    'LEGO Phone Home': '',
    'LEGO Mobile Uplink': '',
    'LEGO Super-Charged Satellite': '',
    'LEGO Niffler': '',
    'LEGO Sinister Scorpion': '',
    'LEGO Vicious Vulture': '',
    'LEGO Swooping Evil': '',
    'LEGO Brutal Bloom': '',
    'LEGO Crawling Creeper': '',
    'LEGO Ecto-1 (2016)': '',
    'LEGO Ectozer': '',
    'LEGO PerfEcto': '',
    'LEGO Flash n Finish': '',
    'LEGO Rampage Record Player': '',
    'LEGO Stripes Throne': '',
    'LEGO R.C. Racer': '',
    'LEGO Gadget-O-Matic': '',
    'LEGO Scarlet Scorpion': '',
    'LEGO Hogwarts Express': '',
    'LEGO Steam Warrior': '',
    'LEGO Soaring Steam Plane': '',
    'LEGO Enchanted Car': '',
    'LEGO Shark Sub': '',
    'LEGO Monstrous Mouth': '',
    'LEGO IMF Scrambler': '',
    'LEGO Shock Cycle': '',
    'LEGO IMF Covert Jet': '',
    'LEGO IMF Sports Car': '',
    'LEGO IMF Tank': '',
    'LEGO IMF Splorer': '',
    'LEGO Sonic Speedster': '',
    'LEGO Blue Typhoon': '',
    'LEGO Moto Bug': '',
    'LEGO The Tornado': '',
    'LEGO Crabmeat': '',
    'LEGO Eggcatcher': '',
    'LEGO K.I.T.T.': '',
    'LEGO Goliath Armored Semi': '',
    'LEGO K.I.T.T. Jet': '',
    'LEGO Police Helicopter': '',
    'LEGO Police Hovercraft': '',
    'LEGO Police Plane': '',
    'LEGO Bionic Steed': '',
    'LEGO Bat-Raptor': '',
    'LEGO Ultrabat': '',
    'LEGO Batwing': '',
    'LEGO The Black Thunder': '',
    'LEGO Bat-Tank': '',
    'LEGO Skeleton Organ': '',
    'LEGO Skeleton Jukebox': '',
    'LEGO Skele-Turkey': '',
    'LEGO One-Eyed Willys Pirate Ship': '',
    'LEGO Fanged Fortune': '',
    'LEGO Inferno Cannon': '',
    'LEGO Buckbeak': '',
    'LEGO Giant Owl': '',
    'LEGO Fierce Falcon': '',
    'LEGO Saturns Sandworm': '',
    'LEGO Haunted Vacuum': '',
    'LEGO Spooky Spider': '',
    'LEGO PPG Smartphone': '',
    'LEGO PPG Hotline': '',
    'LEGO Powerpuff Mag-Net': '',
    'LEGO Mega Blast Bot': '',
    'LEGO Ka-Pow Cannon': '',
    'LEGO Slammin Guitar': '',
    'LEGO Octi': '',
    'LEGO Super Skunk': '',
    'LEGO Sonic Squid': '',
    'LEGO T-Car': '',
    'LEGO T-Forklift': '',
    'LEGO T-Plane': '',
    'LEGO Spellbook of Azarath': '',
    'LEGO Raven Wings': '',
    'LEGO Giant Hand': '',
    'LEGO Titan Robot': '',
    'LEGO T-Rocket': '',
    'LEGO Robot Retriever': '',
}

for index, (name, url) in enumerate(character_names.items(), start=1):
    if url:
        print(f"'{name}': '{url}',")
    else:
        image_url = get_image_url(name, api_key, search_engine_id)
        if image_url:
            print(f"'{name}': '{image_url}',")
        else:
            print(f"'{name}': '',")
